title: HungHsu(Allen)'s E-Porfolio
author: HungHsu(Allen) Chen
url: https://allenlqve.github.io/e-portfolio/ # root address of the site
description: > # description of the site (multiple lines allowed)
  This page is an E-Portfolio for me, Allen, to present the projects that I have done.

permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon

# twitter:
#     username:  # update or delete this
#     card: summary_large_image

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "<-- back" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  # show_footer: true # show footer links in home page,add in _data/home.yml
  show_projects: true # show projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml
  show_reading_time: true # show number of words and reading time in the blog posts
  show_tags: true # show tags in a blog posts
  # options for "home" page
  home:
    title_projects: Portfolio
    title_misc_list: Details

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
